echo main readme content > "readme.txt"
echo another readme > "README.md"
echo source file > "Program.cs"
echo utility > "Utils.cs"
echo helper > "Helper.cs"
echo temp data > "temp.txt"
echo temp cache > "temp.dat"
echo data file > "data.json"
echo config > "app.config"
echo log file > "output.log"
