; MantisZip Installer Script
; Requires Inno Setup 6

#define MyAppName "MantisZip"
#ifndef MyAppVersion
#define MyAppVersion "0.4.4"
#endif
#define MyAppPublisher "MantisZip Contributors"
#define MyAppURL "https://github.com/mantis3d/MantisZip"
#define MyAppExeName "MantisZip.UI.exe"

[Setup]
AppId={{F7A3C8E1-2D4B-4A9F-9C6E-8B5D7A3F2E1C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=LICENSE
OutputDir=installer
OutputBaseFilename=MantisZip-{#MyAppVersion}-Setup-WebSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
ChangesEnvironment=yes
SetupIconFile=src\MantisZip.UI\Resources\App.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinese"; MessagesFile: "setup\Languages\ChineseSimplified.isl"

[CustomMessages]
; English
english.ConfigPageTitle=Installation Options
english.ConfigDesc=Choose your preferred appearance and system integration settings
english.ThemeGroup=Appearance
english.ThemeLight=Light theme
english.ThemeDark=Dark theme
english.ShellGroup=System Integration
english.InstallShell=Add to Windows context menu
english.AssocGroup=File type associations

; Download page (shown before installation begins)
english.DownloadPageCaption=Download required components
english.DownloadPageDescription=MantisZip requires .NET 9 Runtime and WebView2 Runtime to run. They will be downloaded automatically.

; Chinese (Simplified)
chinese.ConfigPageTitle=安装配置
chinese.ConfigDesc=选择偏好的外观和系统集成设置
chinese.ThemeGroup=外观
chinese.ThemeLight=浅色主题
chinese.ThemeDark=深色主题
chinese.ShellGroup=系统集成
chinese.InstallShell=添加到 Windows 右键菜单
chinese.AssocGroup=文件关联
chinese.DownloadPageCaption=正在下载必要组件
chinese.DownloadPageDescription=MantisZip 需要 .NET 9 运行时和 WebView2 运行时才能运行。正在自动下载中。

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
; === All DLLs (wildcard — automatically includes new dependencies) ===
Source: "publish_output\*.dll"; DestDir: "{app}"; Flags: ignoreversion

; === Executables ===
Source: "publish_output\MantisZip.UI.exe"; DestDir: "{app}"; Flags: ignoreversion

; === Debug symbols ===
Source: "publish_output\MantisZip.Core.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish_output\MantisZip.UI.pdb"; DestDir: "{app}"; Flags: ignoreversion

; === Runtime config (required for .NET assembly resolution) ===
Source: "publish_output\MantisZip.UI.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish_output\MantisZip.UI.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion

; === ShellExt COM host (dynamic context menu) — runtimeconfig.json required for COM activation ===
Source: "publish_output\MantisZip.ShellExt.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion

; === 7z.dll (SharpSevenZip): architecture-specific subdirectories ===
Source: "publish_output\x64\7z.dll"; DestDir: "{app}\x64"; Flags: ignoreversion
Source: "publish_output\x86\7z.dll"; DestDir: "{app}\x86"; Flags: ignoreversion

; === Resources (app icon, file type icons, context menu icons, localization) ===
Source: "publish_output\Resources\App.ico"; DestDir: "{app}\Resources"; Flags: ignoreversion
Source: "publish_output\Resources\Icons\*.ico"; DestDir: "{app}\Resources\Icons"; Flags: ignoreversion
Source: "publish_output\Resources\MenuIcons\*.ico"; DestDir: "{app}\Resources\MenuIcons"; Flags: ignoreversion
Source: "publish_output\Resources\strings.en.json"; DestDir: "{app}\Resources"; Flags: ignoreversion
Source: "publish_output\Resources\strings.zh.json"; DestDir: "{app}\Resources"; Flags: ignoreversion
Source: "publish_output\Resources\languages.json"; DestDir: "{app}\Resources"; Flags: ignoreversion

; === Contributor CSV files (generated by GitHub Actions) ===
Source: "publish_output\contributors-technical.csv"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish_output\contributors-financial.csv"; DestDir: "{app}"; Flags: ignoreversion

; === License (7z.dll is distributed under GNU Lesser General Public License) ===
Source: "lgpl.txt"; DestDir: "{app}"; Flags: ignoreversion

; === Prebuilt user settings (copied to %LOCALAPPDATA% on fresh install) ===
; Replace files in installer\prebuilt\ with your own settings from %LOCALAPPDATA%\MantisZip\
Source: "installer\prebuilt\settings.json"; DestDir: "{app}\prebuilt"; Flags: ignoreversion
Source: "installer\prebuilt\window.json"; DestDir: "{app}\prebuilt"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent; WorkingDir: "{app}"

[UninstallRun]
Filename: "{app}\{#MyAppExeName}"; Parameters: "--uninstall-shell"; Flags: runhidden; WorkingDir: "{app}"
Filename: "{app}\{#MyAppExeName}"; Parameters: "--uninstall-assoc"; Flags: runhidden; WorkingDir: "{app}"

[Code]
const
  WebView2RegKey = 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  EvergreenBootstrapperUrl = 'https://go.microsoft.com/fwlink/p/?LinkId=2124703';
  DotNet9RegKey = 'SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.WindowsDesktop.App';
  DotNet9RuntimeUrl = 'https://aka.ms/dotnet/9.0/windowsdesktop-runtime-win-x64.exe';

var
  // Custom wizard page controls
  WPConfigPage: TWizardPage;
  ThemeLightRadio: TNewRadioButton;
  ThemeDarkRadio: TNewRadioButton;
  InstallShellCheck: TNewCheckBox;
  // Per-format association checkboxes
  AssocCheckZip: TNewCheckBox;
  AssocCheck7z: TNewCheckBox;
  AssocCheckRar: TNewCheckBox;
  AssocCheckTar: TNewCheckBox;
  AssocCheckTarGz: TNewCheckBox;
  AssocCheckGz: TNewCheckBox;
  AssocCheckIso: TNewCheckBox;
  // Download progress page
  DownloadPage: TDownloadWizardPage;

// Import Sleep from kernel32 for post-install delay (let .NET registration settle)
procedure Sleep(Milliseconds: DWord); external 'Sleep@kernel32.dll stdcall';

// Create the custom configuration wizard page (theme + system integration)
procedure CreateConfigPage;
var
  ThemeGroupLabel: TNewStaticText;
  ShellGroupLabel: TNewStaticText;
  AssocGroupLabel: TNewStaticText;
  RowTop: Integer;
  RowTop2: Integer;
begin
  WPConfigPage := CreateCustomPage(wpLicense,
    CustomMessage('ConfigPageTitle'),
    CustomMessage('ConfigDesc'));

  // --- Appearance section ---
  ThemeGroupLabel := TNewStaticText.Create(WPConfigPage);
  ThemeGroupLabel.Parent := WPConfigPage.Surface;
  ThemeGroupLabel.Caption := CustomMessage('ThemeGroup');
  ThemeGroupLabel.Font.Style := [fsBold];
  ThemeGroupLabel.Top := 8;
  ThemeGroupLabel.Left := 0;

  ThemeLightRadio := TNewRadioButton.Create(WPConfigPage);
  ThemeLightRadio.Parent := WPConfigPage.Surface;
  ThemeLightRadio.Caption := CustomMessage('ThemeLight');
  ThemeLightRadio.Top := ThemeGroupLabel.Top + ScaleY(20);
  ThemeLightRadio.Left := 16;
  ThemeLightRadio.Checked := True;

  ThemeDarkRadio := TNewRadioButton.Create(WPConfigPage);
  ThemeDarkRadio.Parent := WPConfigPage.Surface;
  ThemeDarkRadio.Caption := CustomMessage('ThemeDark');
  ThemeDarkRadio.Top := ThemeLightRadio.Top + ScaleY(24);
  ThemeDarkRadio.Left := 16;

  // --- System Integration section ---
  ShellGroupLabel := TNewStaticText.Create(WPConfigPage);
  ShellGroupLabel.Parent := WPConfigPage.Surface;
  ShellGroupLabel.Caption := CustomMessage('ShellGroup');
  ShellGroupLabel.Font.Style := [fsBold];
  ShellGroupLabel.Top := ThemeDarkRadio.Top + ScaleY(28);
  ShellGroupLabel.Left := 0;

  InstallShellCheck := TNewCheckBox.Create(WPConfigPage);
  InstallShellCheck.Parent := WPConfigPage.Surface;
  InstallShellCheck.Caption := CustomMessage('InstallShell');
  InstallShellCheck.Top := ShellGroupLabel.Top + ScaleY(20);
  InstallShellCheck.Left := 16;
  InstallShellCheck.Width := WPConfigPage.SurfaceWidth - ScaleX(32);
  InstallShellCheck.Checked := True;

  // --- File type associations (per-format checkboxes) ---
  AssocGroupLabel := TNewStaticText.Create(WPConfigPage);
  AssocGroupLabel.Parent := WPConfigPage.Surface;
  AssocGroupLabel.Caption := CustomMessage('AssocGroup');
  AssocGroupLabel.Font.Style := [fsBold];
  AssocGroupLabel.Top := InstallShellCheck.Top + ScaleY(28);
  AssocGroupLabel.Left := 0;

  RowTop := AssocGroupLabel.Top + ScaleY(20);

  AssocCheckZip := TNewCheckBox.Create(WPConfigPage);
  AssocCheckZip.Parent := WPConfigPage.Surface;
  AssocCheckZip.Caption := '.zip';
  AssocCheckZip.Top := RowTop;
  AssocCheckZip.Left := 16;
  AssocCheckZip.Width := ScaleX(64);
  AssocCheckZip.Checked := True;

  AssocCheck7z := TNewCheckBox.Create(WPConfigPage);
  AssocCheck7z.Parent := WPConfigPage.Surface;
  AssocCheck7z.Caption := '.7z';
  AssocCheck7z.Top := RowTop;
  AssocCheck7z.Left := ScaleX(96);
  AssocCheck7z.Width := ScaleX(64);
  AssocCheck7z.Checked := True;

  AssocCheckRar := TNewCheckBox.Create(WPConfigPage);
  AssocCheckRar.Parent := WPConfigPage.Surface;
  AssocCheckRar.Caption := '.rar';
  AssocCheckRar.Top := RowTop;
  AssocCheckRar.Left := ScaleX(176);
  AssocCheckRar.Width := ScaleX(64);
  AssocCheckRar.Checked := True;

  AssocCheckTar := TNewCheckBox.Create(WPConfigPage);
  AssocCheckTar.Parent := WPConfigPage.Surface;
  AssocCheckTar.Caption := '.tar';
  AssocCheckTar.Top := RowTop;
  AssocCheckTar.Left := ScaleX(256);
  AssocCheckTar.Width := ScaleX(64);
  AssocCheckTar.Checked := True;

  // Row 2
  RowTop2 := RowTop + ScaleY(24);

  AssocCheckTarGz := TNewCheckBox.Create(WPConfigPage);
  AssocCheckTarGz.Parent := WPConfigPage.Surface;
  AssocCheckTarGz.Caption := '.tar.gz';
  AssocCheckTarGz.Top := RowTop2;
  AssocCheckTarGz.Left := 16;
  AssocCheckTarGz.Width := ScaleX(80);
  AssocCheckTarGz.Checked := True;

  AssocCheckGz := TNewCheckBox.Create(WPConfigPage);
  AssocCheckGz.Parent := WPConfigPage.Surface;
  AssocCheckGz.Caption := '.gz';
  AssocCheckGz.Top := RowTop2;
  AssocCheckGz.Left := ScaleX(112);
  AssocCheckGz.Width := ScaleX(64);
  AssocCheckGz.Checked := True;

  AssocCheckIso := TNewCheckBox.Create(WPConfigPage);
  AssocCheckIso.Parent := WPConfigPage.Surface;
  AssocCheckIso.Caption := '.iso';
  AssocCheckIso.Top := RowTop2;
  AssocCheckIso.Left := ScaleX(192);
  AssocCheckIso.Width := ScaleX(64);
  AssocCheckIso.Checked := True;
end;

// Map Inno Setup language code to MantisZip app language code
function GetAppLanguageCode: string;
var
  lang: string;
begin
  lang := ExpandConstant('{language}');
  if lang = 'english' then
    Result := 'en'
  else if lang = 'chinese' then
    Result := 'zh'
  else
    Result := 'en';
end;

// Get selected theme value from custom page
function GetSelectedTheme: string;
begin
  if ThemeDarkRadio.Checked then
    Result := 'Dark'
  else
    Result := 'Light';
end;

// Check functions for conditional [Run] entries
function IsShellInstallChecked: Boolean;
begin
  Result := InstallShellCheck.Checked;
end;

// Returns true if at least one format checkbox is checked
function IsAnyAssocChecked: Boolean;
begin
  Result := AssocCheckZip.Checked or AssocCheck7z.Checked or AssocCheckRar.Checked
         or AssocCheckTar.Checked or AssocCheckTarGz.Checked or AssocCheckGz.Checked
         or AssocCheckIso.Checked;
end;

// Builds comma-separated list of checked extensions for the --install-assoc parameter
function GetAssocParams(Param: string): string;
var
  parts: TStringList;
begin
  parts := TStringList.Create;
  try
    if AssocCheckZip.Checked then parts.Add('.zip');
    if AssocCheck7z.Checked then parts.Add('.7z');
    if AssocCheckRar.Checked then parts.Add('.rar');
    if AssocCheckTar.Checked then parts.Add('.tar');
    if AssocCheckTarGz.Checked then parts.Add('.tar.gz');
    if AssocCheckGz.Checked then parts.Add('.gz');
    if AssocCheckIso.Checked then parts.Add('.iso');
    Result := parts.CommaText;
  finally
    parts.Free;
  end;
end;

// Replace placeholder tokens in the copied settings.json with actual wizard selections.
procedure PatchSettingsThemeAndLanguage(const FileName: String);
var
  Content: AnsiString;
  ContentStr: String;
begin
  if LoadStringFromFile(FileName, Content) then
  begin
    ContentStr := Content;
    StringChange(ContentStr, '__LANG__', GetAppLanguageCode);
    StringChange(ContentStr, '__THEME__', GetSelectedTheme);
    Content := ContentStr;
    SaveStringToFile(FileName, Content, False);
    Log('Settings patched with wizard theme/language selection.');
  end
  else
    Log('Failed to load settings.json for theme/language patching.');
end;

procedure InitializeWizard;
begin
  DownloadPage := CreateDownloadPage(
    CustomMessage('DownloadPageCaption'),
    CustomMessage('DownloadPageDescription'),
    nil);
  CreateConfigPage;
end;

// Check if WebView2 Runtime is already installed.
// Checks multiple registry locations and confirms a version value exists (not just a key).
function IsWebView2Installed: Boolean;
var
  version: string;
begin
  // NOTE: This installer is 32-bit. On 64-bit Windows, HKLM is
  // redirected to WOW6432Node — use HKLM64 for the native 64-bit view.
  Result := RegQueryStringValue(HKLM64, WebView2RegKey, 'pv', version) or
            RegQueryStringValue(HKCU, WebView2RegKey, 'pv', version);
end;

// Check if .NET 9 Desktop Runtime is already installed.
// Checks for any subkey starting with "9." under the WindowsDesktop.App registry path.
function IsDotNet9Installed: Boolean;
var
  subkeys: TArrayOfString;
  i: Integer;
begin
  Result := False;
  // NOTE: This installer is 32-bit. On 64-bit Windows, HKLM is
  // redirected to WOW6432Node — use HKLM64 for the native 64-bit view.
  // .NET 9 Desktop Runtime registers in the native 64-bit registry only.
  if RegGetSubkeyNames(HKLM64, DotNet9RegKey, subkeys) then
  begin
    for i := 0 to GetArrayLength(subkeys) - 1 do
    begin
      if Copy(subkeys[i], 1, 2) = '9.' then
      begin
        Result := True;
        Exit;
      end;
    end;
  end;
end;

// Intercept the "Ready to Install" page — download prerequisites before installation begins.
// The download happens AFTER the user clicks Install but BEFORE file copying.
function NextButtonClick(CurPageID: Integer): Boolean;
var
  NeedDownload: Boolean;
begin
  if CurPageID = wpReady then
  begin
    NeedDownload := False;
    DownloadPage.Clear;
    if not IsDotNet9Installed then
    begin
      DownloadPage.Add(DotNet9RuntimeUrl, 'dotnet-runtime-9.0-win-x64.exe', '');
      NeedDownload := True;
    end;
    if not IsWebView2Installed then
    begin
      DownloadPage.Add(EvergreenBootstrapperUrl, 'MicrosoftEdgeWebview2Setup.exe', '');
      NeedDownload := True;
    end;

    // Only show the download page if there are items to download.
    if NeedDownload then
    begin
      DownloadPage.Show;
      try
        try
          DownloadPage.Download;
          Result := True;
        except
          Result := False;
        end;
      finally
        DownloadPage.Hide;
      end;
    end else
      Result := True;
  end else
    Result := True;
end;

// Install runtimes (already downloaded via DownloadPage)
// Write installer settings to AppData after install completes
procedure CurStepChanged(CurStep: TSetupStep);
var
  BootstrapperPath: string;
  ResultCode: Integer;
  Json: string;
  SettingsDir: string;
  SettingsFile: string;
  WindowFile: string;
  i: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    // 1. First: .NET 9 Desktop Runtime (more critical — app won't start without it)
    // File was already downloaded via DownloadPage before installation began.
    if not IsDotNet9Installed then
    begin
      BootstrapperPath := ExpandConstant('{tmp}\dotnet-runtime-9.0-win-x64.exe');
      if FileExists(BootstrapperPath) then
      begin
        Log('Installing .NET 9 Desktop Runtime...');
        if Exec(BootstrapperPath, '/quiet /install /norestart', '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then
        begin
          if ResultCode = 0 then
          begin
            Log('.NET 9 Desktop Runtime installed successfully.');
            // Wait for .NET registry registration to complete before running
            // shell/assoc registration (which also launch MantisZip.exe).
            // The installer process exits before the registry is fully synced.
            i := 0;
            while (i < 60) and (not IsDotNet9Installed) do
            begin
              Sleep(500);
              i := i + 1;
            end;
            if IsDotNet9Installed then
              Log('.NET registration confirmed after ~' + IntToStr(i * 500) + 'ms')
            else
              Log('.NET registration not detected after ~30s, proceeding anyway');
          end
          else
            Log('.NET 9 Desktop Runtime installer exited with code: ' + IntToStr(ResultCode));
        end
        else
          Log('Failed to launch .NET 9 bootstrapper.');
      end
      else
        Log('.NET 9 bootstrapper not found. Download may have failed; user may need to install manually.');
    end
    else
      Log('.NET 9 Desktop Runtime is already installed.');

    // 2. Then: WebView2 Runtime
    if not IsWebView2Installed then
    begin
      BootstrapperPath := ExpandConstant('{tmp}\MicrosoftEdgeWebview2Setup.exe');
      if FileExists(BootstrapperPath) then
      begin
        Log('Installing WebView2 Runtime...');
        if Exec(BootstrapperPath, '/silent /install', '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then
        begin
          if ResultCode = 0 then
            Log('WebView2 Runtime installed successfully.')
          else
            Log('WebView2 Runtime installer exited with code: ' + IntToStr(ResultCode));
        end
        else
          Log('Failed to launch WebView2 bootstrapper.');
      end
      else
        Log('WebView2 bootstrapper not found. Download may have failed; user may need to install manually.');
    end
    else
      Log('WebView2 Runtime is already installed.');

    // 3. Register shell extensions and file associations.
    // These run MantisZip.exe, which requires .NET 9, so they must happen
    // AFTER the .NET registration wait above.
    if InstallShellCheck.Checked then
    begin
      Log('Registering context menu...');
      if Exec(ExpandConstant('{app}\MantisZip.UI.exe'), '--install-shell', '',
        SW_SHOW, ewNoWait, ResultCode) then
        Log('Context menu registration initiated.')
      else
        Log('Failed to launch --install-shell.');
    end;
    if IsAnyAssocChecked then
    begin
      Log('Registering file associations...');
      if Exec(ExpandConstant('{app}\MantisZip.UI.exe'),
        '--install-assoc ' + GetAssocParams(''),
        '', SW_SHOW, ewNoWait, ResultCode) then
        Log('File association registration initiated.')
      else
        Log('Failed to launch --install-assoc.');
    end;

    SettingsDir := ExpandConstant('{localappdata}\MantisZip');
    SettingsFile := SettingsDir + '\settings.json';
    WindowFile := SettingsDir + '\window.json';

    // Only write on fresh install — don't overwrite existing user settings on upgrade
    if not FileExists(SettingsFile) then
    begin
      Log('Writing prebuilt settings to: ' + SettingsDir);
      if not DirExists(SettingsDir) then
        CreateDir(SettingsDir);

      // Copy prebuilt settings.json (including Language + Theme from wizard)
      // Users can replace installer\prebuilt\ with their own files before building the installer
      if CopyFile(ExpandConstant('{app}\prebuilt\settings.json'), SettingsFile, False) then
      begin
        Log('Prebuilt settings.json copied.')
        // Override placeholder tokens with actual wizard selections
        PatchSettingsThemeAndLanguage(SettingsFile);
      end
      else
      begin
        Log('Failed to copy prebuilt settings.json, writing minimal config...');
        // Fallback: write minimal settings (Language + Theme from wizard)
        Json := '{' +
          '"Language": "' + GetAppLanguageCode + '",' +
          '"Theme": "' + GetSelectedTheme + '"' +
          '}';
        SaveStringToFile(SettingsFile, Json, False);
      end;

      // Copy prebuilt window.json if it exists
      if FileExists(ExpandConstant('{app}\prebuilt\window.json')) then
      begin
        if CopyFile(ExpandConstant('{app}\prebuilt\window.json'), WindowFile, False) then
          Log('Prebuilt window.json copied.')
        else
          Log('Failed to copy prebuilt window.json.');
      end;
    end
    else
      Log('Settings file already exists, preserving existing user settings.');
  end;
end;
